export const SET_SEARCHED_MOVIES = "SET_SEARCHED_MOVIES"
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES"
export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES"
export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES"
export const SET_SEARCHED_HISTORY = "SET_SEARCHED_HISTORY"
export const SET_MOVIE = "SET_MOVIE"


